[package]
name = "systems"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = { git = "https://github.com/bevyengine/bevy.git", rev = "7ad5fb7"}#, features = ["dynamic_linking"] }
noise = "0.9.0"
